version: '3.3'
services:
  app:
    build:
      context: .
    ports:
      - '4567:4567'
    volumes:
      - ./:/jwt-api-sinatra
    env_file: .env.db
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.db'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres:
