version: '3.3'
services:
  app:
    build:
      context: .
    ports:
      - '4567:4567'
    volumes:
      - ./:/jwt-api-sinatra
    env_file: .env.db
    depends_on:
      - mongo
    links:
      - mongo
  
  mongo:
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    env_file: .env.db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo
