development:
  clients:
    default:
      database: sinatra_api_development
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: sinatra_api_test
      hosts:
        - mongo:27017
